/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as external from "./external";
export type { external };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as koalasSol from "./koalas.sol";
export type { koalasSol };
