/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKoalasDescriptor } from "./IKoalasDescriptor";
export type { IKoalasSeeder } from "./IKoalasSeeder";
export type { IKoalasToken } from "./IKoalasToken";
