/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKoalasDescriptor__factory } from "./IKoalasDescriptor__factory";
export { IKoalasSeeder__factory } from "./IKoalasSeeder__factory";
export { IKoalasToken__factory } from "./IKoalasToken__factory";
